-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJiVu7kFg7vfFQTDk
jjjGv6fWalqL9y7xqxCbldLgTe2gCgYIKoZIzj0DAQehRANCAAT9Axq58FSPUtxU
vongfOFkjzJRnw9Mpt3zPAcZ5juPS2QCqQ2P846jWShf+AkEBAJTmmDqqsOQSsE9
G2mLtoUO
-----END PRIVATE KEY-----